apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: login-demo
  name: login-demo
spec:
  ports:
  - name: 8089-8089
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: login-demo
  type: ClusterIP
status:
  loadBalancer: {}
